### ISSUE TITLE
improve layout

### ISSUE THREAD

**Issue by mmiat** [TravisSpangle/redmine_spent_time_in_issue_description#24]
I suggest to nowrap "spento on", "user" and "hours"

**Comment by mmiat** [comment]
I've added to css this code:

```css
/* Stili Tabella */
table.issue-spent-time-description { border-collapse: collapse; }
table.issue-spent-time-description tr td { border: 2px solid #ffffff; padding: 3px; }
table.issue-spent-time-description tr:nth-child(odd) td { background: #FFFFBD; }
table.issue-spent-time-description tr:nth-child(even) td { background: #FFFF79; }
table.issue-spent-time-description tr:hover td { background-color: #CCCCFF; }

/* Tengo il contenuto delle celle selezionate sulla stessa righa */
table.issue-spent-time-description tr td:nth-child(1),
table.issue-spent-time-description tr td:nth-child(2),
table.issue-spent-time-description tr td:nth-child(3),
table.issue-spent-time-description tr td:nth-child(6) { white-space: nowrap; }
```

it's an alpha version :)
